routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('candidates', 'CandidatesController')->middleware('auth');
Route::get('candidates/changeuser/{cid}/{uid?}', 'CandidatesController@changeUser')->name('candidate.changeuser');
Route::get('candidates/changestatus/{cid}/{sid}', 'CandidatesController@changeStatus')->name('candidates.changestatus')->middleware('auth');
Route::get('mycandidates', 'CandidatesController@myCandidates')->name('candidates.mycandidates')->middleware('auth');
Route::resource('interviews', 'InformationController')->middleware('auth');
Route::get('myinterviews', 'InformationController@myInterviews')->name('interviews.myinterviews')->middleware('auth');
Route::get('candidates/delete/{id}', 'CandidatesController@destroy')->name('candidate.delete');

Route::get('/hello', function (){
    return 'Hello Larevel';
}); 

Route::get('/student/{id}', function ($id  = 'No student found'){
    return 'We got student with id '.$id;
});

Route::get('/car/{id?}', function ($id  = null){
    if(isset($id)){
        //TODO: validate for integer  
        return "We got car $id";
    } else {
        return 'We need the id to find your car';
    }
});


Route::get('/comment/{id}', function ($id) {
    return view('comment', compact('id'));
});

Route::get('/users/{email}/{name?}', function ($email,$name = null) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});
#example
Route::get('/users1/{name?}/{email}', function ($name = null, $email) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/interviews/create.blade.php
@extends('layouts.app')

@section('title', 'Create candidate')

@section('content')
        <h1>Create interview</h1>
        <form method = "post" action = "{{action('InformationController@store')}}">
        @csrf
        
        <label for = "interviewer">Interviewer name</label>
        <select class="form-control" name="interviewer_id">
        @foreach($interviewer as $interviewer)
        @if(isset($interviewer->id))
        <option value=" {{$interviewer->id}} ">{{$interviewer->name}}</option>
        @else
            Assign owner
        @endif 
        @endforeach 
        </select>
        </br>
        <label for = "Candidate">Candidate Name</label>
        <select class="form-control" name="candidate_id">
        @foreach($candidates as $candidate)
        @if(isset($candidate->id))
        <option value=" {{$candidate->id}} ">{{$candidate->name}}</option>  
        @else
            Assign owner
        @endif
        
        @endforeach
        </select>
        </br>
        <div class="form-group">
            <label for = "date">Date</label>
            <input type="date" name="date" id="date" class="form-control" value="{{ date("Y-m-d") }}" required />
        <div class="form-group">
        </br>
            <label for = "information">Information</label>
            <input type = "text" class="form-control" name = "information">
        </div> 
        <div>
            <input type = "submit" name = "submit" value = "Create interview">
        </div>                       
        </form>    
@endsection

resources/views/interviews/index.blade.php
@extends('layouts.app')


@section('content')

<div><a href="{{route('interviews.create')}}">Create New Interview</a></div>
<h1>List Of Interviews</h1>

<table class = "table">
    <tr>
    <th>Candidate Name</th><th>Interviewer Name</th><th>Date</th><th>Information</th>
    <!-- the table data -->
    @foreach($interviews as $interview)
        <tr>
            <td></td>
            <td></td>
            <td>{{$interview->date}}</td>
            <td>{{$interview->information}}</td>                                                           
        </tr>
    @endforeach
</table>
@endsection